version: '3.4'
services:
  typesense:
    image: typesense/typesense:0.26.0.rc67
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
